name: 'Codyze'
description: 'Greet someone and record the time'
inputs:
  directory:  # id of input
    description: 'Who to greet'
    required: true
    default: 'src/main/java'
  version:
    description: The Codyze version
    required: true
    default: 1.4.1
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'
